# Simple workflow for building static content from source
name: Build and deploy documentation on Pages

on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
  workflow_call:
    inputs:
      python-version:
        required: false
        default: '3.12'
        type: string

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: 'Install Python ${{ inputs.python-version }}'
        uses: actions/setup-python@v5
        with:
          python-version: '${{ inputs.python-version }}'
      - name: Install dependencies
        shell: sh
        run: |
          echo ::group::Install Python requirements
          pip install -r requirements.txt
          echo ::endgroup::
      - name: Build static content from source
        shell: sh
        run: |
          echo ::group::Generate docs website
          mkdocs build -d site/
          echo ::endgroup::
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          # Upload entire repository
          path: 'site/'
  deploy:
    needs: [build]
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
