name: Another sample workflow

on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_call:

jobs:
  hello-world:
    runs-on: ubuntu-latest
    steps:
      - name: Hello world
        shell: sh
        run: |
          echo 'Hello world'
